language: php

php:
  - 5.5
  - 5.6
  - 7

install:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - vendor/bin/phpunit --testsuite unit --coverage-clover build/logs/clover.xml

after_script:
  - bash bin/codeclimate.sh
