language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer self-update
  - composer install --no-interaction

addons:
  code_climate:
    repo_token:
      secure: "FEs0lC5e3paSb88frA230adPtOtMN/S+l8jQo7VNgOnGgJgVCA4EXLX+YwWOgUokbjssxI8HA3D4Q55nrW8vUAkV3QYJJSrL+c5+IBxblD186kr7xgXtcLvgxDf5yOL2pjLtJ5EnnObL4cb8yS9AlaCJNz113OImAIcLaUwcz0DvLk+XYPp6gLikPfew539Xd4nHn8DbAPhFNCoHyBJqvHHaS+iBzJipd1xrrIH4nHySks3Nar5m7GdLvQ4HzZs3m9g++E/fe96nBu8am9xBYBTFfyLDJH4ugkRxiNBhJ3YCLKcSHgni6WxWigefaa5axYMdkVlThNXaCnwRwapYbGKB6ml7IlMPQyrTdzRoEAV9xFPq22JERQCVoTq5hLN4UTYCecNaOUBfj0X810FyYQIyUneC6wF/IS8e4vrmoYhtVozSLUqStSHvJxBBvWDmhOH4CRjM8JVk2b1c/Rh4Mptml6q/cxRwpdyI3LJKFbhsWG0OBa5WXzO5DGjs8MweG0oVVAiIwjIAyY803xq557CHEsKyK0nEieHyDn64LPQBRTD0qwDEzAINpyK9okIvk90HqSuEywljTFc+jDCrMIJAqBJT2/c4cS9/J8Q3sHV+p36p7MvJZYLwLhBu1lJrkZXq4SV36VruSi95qoFMeoEI5e/cwwqZ8lOzcdOM9j4="

before_script: chmod +x ./codeclimate.sh

after_script: ./codeclimate.sh
